OffchainLabs/bold

- chain-abstraction/interfaces.go
- chain-abstraction/sol-implementation/BUILD.bazel
- chain-abstraction/sol-implementation/edge_challenge_manager_test.go
- challenge-manager/edge-tracker/tracker.go
- layer2-state-provider/provider.go
- testing/mocks/mocks.go
- testing/mocks/state-provider/layer2_state_provider.go
This PR adds a test that updates config values in the rollup admin in the middle of a challenge and ensures one step proofs can still be successful
> Test Config Upgrades Mid-Challenge

- contracts/src/challengeV2/libraries/ChallengeEdgeLib.sol
- contracts/src/challengeV2/libraries/ChallengeErrors.sol
- contracts/src/challengeV2/libraries/EdgeChallengeManagerLib.sol
- contracts/test/challengeV2/EdgeChallengeManager.t.sol
- contracts/test/challengeV2/EdgeChallengeManagerLib.t.sol
To reproduce the issue, on b4394ba10fb6b1432b2e0de7bbe106edbbd2915d run
```
forge test --match-test testRevertConfirmAnotherRival
```
This PR fixes the issue by adding `rivalConfirmed` mapping to track if any rival with the same mutual id is confirmed, and prevent edge from confirming if there is one confirmed already.
> fix: only 1 edge can be confirmed per mutual id

- contracts/src/challengeV2/libraries/ChallengeEdgeLib.sol
- contracts/test/challengeV2/EdgeChallengeManager.t.sol
All zero layer edges can contain stake - so we need to allow refunding on all of them
> Removed  block check from setrefunded

- .gitignore
- contracts/package.json
requires lcov to be installed in the system
> chore: add contracts coverage script

- assertions/scanner_test.go
- chain-abstraction/interfaces.go
- chain-abstraction/sol-implementation/edge_challenge_manager.go
- challenge-manager/BUILD.bazel
- challenge-manager/chain-watcher/watcher.go
- challenge-manager/challenge-tree/generalized_path_timer.go
- challenge-manager/challenge-tree/generalized_path_timer_test.go
- challenge-manager/challenge-tree/tree.go
- challenge-manager/challenge-tree/tree_test.go
- challenge-manager/challenges.go
- challenge-manager/manager.go
- challenge-manager/manager_test.go
- containers/threadsafe/map.go
- testing/BUILD.bazel
- testing/mocks/mocks.go
- testing/mocks/state-provider/history_provider_test.go
- testing/mocks/state-provider/layer2_state_provider.go
- testing/mocks/state-provider/layer2_state_provider_test.go
- testing/rollup_config.go
This PR cleans up some technical debt and removes some older references to hardcoded number of challenge levels. This also adds more configuration options to allow for N big step levels in the Go code
> Cleanup Logic to Support Many Subchallenge Levels

- challenge-manager/chain-watcher/BUILD.bazel
- challenge-manager/chain-watcher/watcher.go
- challenge-manager/chain-watcher/watcher_test.go
- challenge-manager/challenge-tree/tree.go
- deps.bzl
- go.mod
- go.sum
This PR aims to optimize the `processEdgeAddedEvent` function by implementing an LRU cache, referred to as junkCommitmentCache. This cache stores composite keys made from `startCommitment` and `startHeight` for edges that don't agree with the start commitment (AgreesWithStartCommit is false). By doing this, the function can quickly short-circuit and avoid redundant and expensive operations when encountering these "junk" commitments again.
> Add LRU Cache for `agreesWithStart` in `AddEdge`

- testing/endtoend/internal/backend/anvil_local.go
This PR updates anvil port to non-default to avoid conflict with more production like instances
> Update anvil port to non-default

- state-commitments/prefix-proofs/prefix_proofs.go
- state-commitments/prefix-proofs/prefix_proofs_test.go
Add more tests to prefix proofs
Deleted a function that's not used in productions `VerifyPrefixProof`
> Add more tests for prefix proofs

- chain-abstraction/sol-implementation/edge_challenge_manager.go
- challenge-manager/chain-watcher/watcher.go
- challenge-manager/edge-tracker/tracker.go
- challenge-manager/manager_test.go
This PR fixes a flake by instead manually adding edges to the chain watcher during a unit test to prevent races. This allows us to verify tests such as `HasConfirmableAncestor`
> Improve Flakey Challenge Manager Tests

- assertions/poster.go
- assertions/scanner.go
- assertions/scanner_test.go
- chain-abstraction/sol-implementation/BUILD.bazel
- chain-abstraction/sol-implementation/assertion_chain.go
- chain-abstraction/sol-implementation/edge_challenge_manager.go
- chain-abstraction/sol-implementation/transact.go
- challenge-manager/chain-watcher/watcher.go
- challenge-manager/edge-tracker/tracker.go
- challenge-manager/manager.go
- challenge-manager/manager_test.go
- testing/endtoend/basic_local_test.go
We should be estimating gas before sending txs through our chain abstraction, as this will catch errors early without us having to spend the funds to do so. This PR also adds protections for places where we might be using a time.Duration of 0, which would cause a runtime panic.
> Estimate Gas Before Sending Txs + Add Minor Protections

- chain-abstraction/BUILD.bazel
- chain-abstraction/interfaces.go
- chain-abstraction/sol-implementation/BUILD.bazel
- chain-abstraction/sol-implementation/assertion_chain.go
- chain-abstraction/sol-implementation/assertion_chain_helper_test.go
- chain-abstraction/sol-implementation/edge_challenge_manager.go
- chain-abstraction/sol-implementation/tracked_contract_backend.go
- chain-abstraction/sol-implementation/tracked_contract_backend_test.go
- testing/endtoend/basic_local_test.go
- testing/mocks/mocks.go
This PR includes a `TrackedContractBackend` type which wraps around `ContractBackend` and can keep track of number of eth calls and txs by method along with gas used per call. This is helpful for optimizing how much we need data from L1 and figuring out where we are making unnecessary calls. At the end of an e2e test, we print out the metrics from the honest validator.
It can be enabled by starting an assertion chain with `WithTrackedContractBackend()` as an option.
Methods with the largest number of calls, with the current config values that trigger edge actions at very fast intervals (250 milliseconds)
- GetEdge (197,858)
- GetAssertion (68,259)
- ConfirmedRival (15,325)
- NumBigStepLevel (10,508)
- ChallengePeriodBlocks (15,291)
- CalculateMutualId (25,832)
- GetPrevAssertionHash …
> Include a TrackedContractBackend to Gather L1 Usage Metrics

- testing/endtoend/basic_local_test.go
Adds e2e tests that will have two validators disagree at the last opcode, and in the middle of a block for sanity
> Add E2E Test to Check Divergence at Last Opcode and In Middle of Block

- assertions/BUILD.bazel
- assertions/poster.go
- assertions/poster_test.go
- assertions/scanner.go
- assertions/scanner_internals_test.go
- assertions/scanner_test.go
- chain-abstraction/sol-implementation/assertion_chain.go
- challenge-manager/manager.go
- layer2-state-provider/provider.go
- runtime/retry.go
- testing/endtoend/basic_local_test.go
- testing/setup/rollup_stack.go
This PR fixes several flaws and bad assumptions we make in how we deal with posting and scanning for assertions posted to the rollup contracts.
When we see an assertion creation event, we now do the following:
- We fetch its claimed execution state. If we are still catching up to the chain, we return an error ErrCatchingUp
- If we agree with it, we log that we agree and do nothing else
- If we disagree, we try to post a rival assertion to it and initiate a challenge if we are configured to do so
It's important to note the last point isn't as simple as it seems. Consider the following scenario where the latest assertion creation event we receive is `D`.
```mermaid
graph LR;
A-->B;
B-->C;
C-->D;
```
However, we _also_ disagree with `C`! Instead, we need to look back until we find the latest …
> Revamp Assertion Service for Production

- challenge-manager/challenges.go
- challenge-manager/manager.go
- tools/fund-weth/BUILD.bazel
- tools/fund-weth/main.go
Avoid challenging assertions again if we have already done so with a simple, in-memory set
> Skip Challenging Assertion Again

- assertions/scanner.go
- challenge-manager/challenge-tree/generalized_path_timer.go
- challenge-manager/edge-tracker/tracker.go
- challenge-manager/manager.go
This PR improves some of the most common error logs that occur when running a BOLD challenge on testnet. It makes the following changes:
- We try to confirm an assertion by time, and if it fails, we then wait some specified amount of time before retrying. However, this leads to execution revert logs. Instead, we should make this onchain tx only if the assertion is confirmable by time
- If an edge does not have a lower child when computing timers, we shouldn't necessarily error. Instead, most of the time this error happens is because we have not yet processed the child creation event, which some other validator may have created. We turn it into an info log
- We log how long an assertion has to wait before it is confirmable by time
- We change a wrong `avgTimeForBlockCreation` default value …
> Improve BOLD Log and Assertion Confirmation UX

- challenge-manager/chain-watcher/watcher_test.go
- challenge-manager/challenge-tree/ancestors_test.go
- challenge-manager/challenge-tree/generalized_path_timer.go
- challenge-manager/challenge-tree/generalized_path_timer_test.go
Previously when calculating the path timer we were including the unrivaled time of the prev assertion, we should instead be using the unrivaled time of the claimed assertion. This lead to some instances where it appeared an edge could be confirmed when in fact it couldnt.
> Updated path timer to check claim id rather than prev

- containers/in-progress-cache/BUILD.bazel
- containers/in-progress-cache/cache.go
- containers/in-progress-cache/cache_test.go
- go.mod
- layer2-state-provider/BUILD.bazel
- layer2-state-provider/history_commitment_provider.go
In BOLD, when interacting with a state provider, we make very expensive computational requests. Sometimes, we may end up making the same request twice as BOLD has several places that process data concurrently.
One example is in computing subchallenges, which is a very expensive computation that can last hours. If an in-flight request is being computed, and another is requested for the same data, we want to use the result of the ongoing one instead of spawning a new computation. This PR adds an "in-progress cache" generic container that leverages this idea. Inspired by https://rauljordan.com/reuse-expensive-computation-with-in-progress-caches/
```go
type InProgressCache[K comparable, V any] struct
// Compute an expensive closure, and if the same request is used to the cache while one is …
```
> Add In-Progress Cache for Expensive Computation

- challenge-manager/challenges.go
This was causing the issue of Block challenge, root edge not found in API
> Fix addBlockChallengeLevelZeroEdge return value

- api/backend/BUILD.bazel
- api/backend/backend.go
- api/types.go
- challenge-manager/edge-tracker/tracker.go
- challenge-manager/manager.go
- containers/fsm/fsm.go
- testing/endtoend/e2e_test.go
This PR shows a tracked edge's FSM in the API results when querying for it. This is helpful for us to understand if an edge is stuck in a certain state and with a certain error due to a bug, and allows us to diagnose the problems faster. It is important in situations when we don't know why an edge is not getting bisected and the actual error message
> Show a Tracked Edge's Finite State Machine in API Results

- assertions/scanner.go
- challenge-manager/challenges.go
- challenge-manager/manager.go
- challenge-manager/types/interfaces.go
This PR improves the assertion confirmation conditions, as they were quite messy and were missing several important details.
Assertions are confirmed by the assertion manager component of the BOLD code. It will try to confirm assertions by time using a ticker until the confirmation occurs. However, there were some problems:
- We were missing a check that the previous assertion must be the latest confirmed
- We were fetching onchain, immutable data on each tick of the goroutine
- It is possible that the parent assertion of a challenge is confirmed by time, but our current code was not considering that
- We should exit if the assertion is claimed in a challenge, as in that case it should be confirmed by winning edge id
> Improve Assertion Confirmation Conditions

- api/db/db.go
- api/db/db_test.go
- assertions/scanner.go
This check was preventing edges from being saved to the DB, which would cause a lot of problems for the validator
> Prevent Assertion Not Yet in DB From Blocking Call to InsertEdge

- api/db/BUILD.bazel
- assertions/BUILD.bazel
- assertions/scanner.go
- assertions/scanner_test.go
If we have a situation like this:
```
/--B--C--D(evil)
A
```
where an honest Alice has not yet participated, if we she sees `D`, she will backtrack and post an honest rival to `B`. However, if the evil chain keeps growing, she will attempt that same routine again and try to submit an already existing rival to `B` and challenge again, wasting resources and time. We add a check that skips this duplicate submission even if we see a growing, evil assertion chain.
> Skip Submitting Rival, Honest Assertions if Observing an Assertion from an Evil Fork

- challenge-manager/edge-tracker/tracker.go
Edge should only despawn if confirmed or if claimed assertion of honest party is confirmed. Fixes a small race that would otherwise occur
> Simplify ShouldDespawn Condition for Edges

- .github/workflows/go.yml
- contracts/scripts/files/localConfig.json
bold upgrade CI test is broken because testnode addresses changed. 
for future reference, gathered addresses like this:
```
#!/bin/bash
PROXY_ADMIN_SLOT="0xb53127684a568b3173ae13b9f8a6016e243e63b6e8ee1178d6a717850b5d6103"
addresses=$(docker exec nitro-testnode-sequencer-1 cat /tokenbridge-data/l1l2_network.json)
contracts=$(echo $addresses | jq -r '.l2Network.ethBridge')
bridge=$(echo $contracts | jq -r '.bridge')
proxyAdmin=$(cast storage $bridge $PROXY_ADMIN_SLOT)
proxyAdmin="0x${proxyAdmin: -40}"
upgradeExecutor=$(cast call $proxyAdmin "owner()")
upgradeExecutor="0x${upgradeExecutor: -40}"
rollup=$(echo $contracts | jq -r '.rollup')
rollupEventInbox=$(cast call $rollup "rollupEventInbox()")
rollupEventInbox="0x${rollupEventInbox: -40}"
contracts=$(echo $contracts | jq …
```
> update testnode addresses

- contracts/src/rollup/IRollupCore.sol
- contracts/src/rollup/IRollupLogic.sol
- contracts/src/rollup/RollupCore.sol
- contracts/src/rollup/RollupUserLogic.sol
- contracts/test/Rollup.t.sol
- contracts/test/signatures/RollupUserLogic
This PR introduce a feature to pin a withdrawal address on creating a new stake (similar to how beacon chain withdrawal credential works), and thus reducing this risk of having a hot private key in the validator software. Note that a compromised key can still lead to a full slashing.
Withdrawal address can only be changed upon full unstake.
TODO: events, tests
> feat: fixed withdrawal address

- contracts/src/challengeV2/libraries/EdgeChallengeManagerLib.sol
- contracts/test/challengeV2/EdgeChallengeManager.t.sol
previously, if you try to confirm an edge that was already confirmed, you'd get `RivalEdgeConfirmed(0x123,0x123)`, which is misleading (and scary) at first glance.
reordering 2 internal calls will result in an `EdgeNotPending` error instead, which is more accurate.
> Throw `EdgeNotPending` instead of `RivalEdgeConfirmed` when trying to confirm an already confirmed edge

- contracts/src/precompiles/ArbOwner.sol
- contracts/src/precompiles/ArbWasm.sol
- contracts/src/state/Deserialize.sol
- contracts/src/state/Module.sol
changes from ecb46c1f to 77ee9de0 in nitro-contracts
(i ignored `src/challenge`, non `sol` files, and tests)
> Merge stylus ecb46c1f to 77ee9de0

- challenge-manager/chain-watcher/watcher.go
- challenge-manager/manager.go
While our chain watcher is scraping events from the latest confirmed assertion to chain head, we want to have our edge trackers "act" as fast as it is reasonable (1s). Then, once we are caught up, we instead just have edge trackers act on each new block notification
> Fast Sync a Validator While Chain Watcher Catching Up

- api/backend/BUILD.bazel
- api/backend/backend.go
- assertions/confirmation.go
- assertions/sync.go
- chain-abstraction/interfaces.go
- chain-abstraction/sol-implementation/BUILD.bazel
- chain-abstraction/sol-implementation/assertion_chain.go
- chain-abstraction/sol-implementation/assertion_chain_test.go
- challenge-manager/chain-watcher/watcher.go
- challenge-manager/challenges.go
- testing/mocks/mocks.go
When we post an assertion, we check if it already exists based on the finalized state. However, if it already exists based on the _latest_ block, we will get a bunch of annoying execution reverted `EXPECTED_ASSERTION_SEEN` logs. In fact, if the assertion exists based on latest head, we should be fine here. When we perform the existence check before posting, we should use the `latest` block for this.
This also checks that the latest confirmed assertion is the parent of an assertion we are trying to confirm, by using latest head to get rid of execution reverts.
> Fix Assertion Posting / Confirmation Reverts

- assertions/BUILD.bazel
- assertions/manager_test.go
Fixes CI flakiness for assertions/
```
//assertions:assertions_test                                             PASSED in 4.6s
Stats over 10 runs: max = 4.6s, min = 4.0s, avg = 4.1s, dev = 0.2s
Executed 1 out of 1 test: 1 test passes.
```
had an 80% failure rate before
> Fix Fast Confirm Assertions Flake

- api/db/BUILD.bazel
- assertions/BUILD.bazel
- chain-abstraction/sol-implementation/BUILD.bazel
- challenge-manager/BUILD.bazel
- challenge-manager/chain-watcher/BUILD.bazel
- challenge-manager/challenge-tree/BUILD.bazel
- containers/BUILD.bazel
- containers/events/BUILD.bazel
- containers/fsm/BUILD.bazel
- containers/threadsafe/BUILD.bazel
- layer2-state-provider/BUILD.bazel
- math/BUILD.bazel
- runtime/BUILD.bazel
- state-commitments/history/BUILD.bazel
- state-commitments/inclusion-proofs/BUILD.bazel
- state-commitments/prefix-proofs/BUILD.bazel
- testing/mocks/state-provider/BUILD.bazel
- time/BUILD.bazel
This will cause us to deliberately decide if we need to increase the
test size if they get bigger. It also prevents a warning in the
output of `bazel test //...`
Intentionally ignoring the in-progress cache as it is going away
in #689
> Add test sizes to small test targets.

- math/BUILD.bazel
- math/intlog2.go
- math/intlog2_test.go
The current practice of converting the uint64 to a float64 and passing it to math.Log2() and then converting the result back to an int is about 18x slower on my M3 MacPro
```
❯ go test . --fuzz=Fuzz --fuzztime 45s
fuzz: elapsed: 0s, gathering baseline coverage: 0/5 completed
fuzz: elapsed: 0s, gathering baseline coverage: 5/5 completed, now fuzzing with 12 workers
fuzz: elapsed: 3s, execs: 748073 (249310/sec), new interesting: 1 (total: 6)
fuzz: elapsed: 6s, execs: 1529140 (260330/sec), new interesting: 1 (total: 6)
fuzz: elapsed: 9s, execs: 2306601 (259140/sec), new interesting: 1 (total: 6)
fuzz: elapsed: 12s, execs: 3091550 (261720/sec), new interesting: 1 (total: 6)
fuzz: elapsed: 15s, execs: 3879652 (262634/sec), new interesting: 1 (total: 6)
fuzz: elapsed: 18s, execs: 4659101 …
```
> Introduce a more efficient Log2 for the uint64 type

- .github/workflows/fuzz.yml
- .github/workflows/go.yml
This also updates the version of go to the 1.21 series because the code on one of the branches is using max which was introduced in 1.21.
> Update the github actions for CI

- challenge-manager/BUILD.bazel
- challenge-manager/challenge-tree/paths.go
Unfortunately, the linter led Pepper to make the problem it was pointing out worse rather than better, and CI didn't run the e2e_test, so we didn't notice it before merging.
FYI, the modification to the BUILD.bazel file is unrelated, and was automatically made with `bazel run //:gazelle`.
> Fix the e2e_test on main

- challenge-manager/manager.go
- challenge-manager/stack.go
- testing/endtoend/BUILD.bazel
- testing/endtoend/e2e_test.go
- testing/endtoend/headers.go
The desire is to be able to be responsive to new blocks as they are created on the parent chain. There was some concern about relying on websockets for this feed of headers, but nitro already has an inprocess abstraction which provides a stream of parent-chain block headers.
The nitro codebase already has an implementation of the HeaderProvider interface that can be passed into the challenge stack, and a tivial one has been added for the end2end testing. Perhaps, after we merge the repos, we can just use the real implementation from the nitro codebase in the e2e_test.go
Part of NIT-2793
> Allow a HeaderProvider to be passed to the stack

- assertions/manager.go
- assertions/poster.go
- chain-abstraction/interfaces.go
- chain-abstraction/sol-implementation/assertion_chain.go
- challenge-manager/BUILD.bazel
- challenge-manager/manager.go
- challenge-manager/manager_test.go
- testing/mocks/mocks.go
Specifically, calculates the number of assertions that are needed per challenge period based on the number of blocks in a challenge period and the minimum number of blocks required between assertions.
This PR is related to NIT-2955
> Base the size of caches on chain configuration

- assertions/manager.go
- assertions/manager_test.go
- assertions/poster_test.go
- assertions/sync_test.go
- layer2-state-provider/provider.go
- testing/mocks/mocks.go
- testing/mocks/state-provider/layer2_state_provider.go
- testing/setup/rollup_stack.go
This makes the code to implement the ExecutionStateAfterPreviousState more complicated than it needs to be for an edge case (bootstrapping a new chain) that will not only happen infrequently, but, can also be represented with a non-nil zero-value `protocol.GoGlobalState{}` instance.
> Disallow nil as an option for the previousGlobalState

- testing/endtoend/backend/anvil_local.go
- testing/setup/rollup_stack.go
Of particular interest for the bold protocol, this now allows test authors to pass in a minimumAssertionPeriod. That can be important in proving that overflow assertions do not require waiting for the minimum assertion period number of blocks between the previous assertion and their own.
Part of NIT-2794
> Add support for configuring the rollup stack deployment

- assertions/poster.go
Previously, `waitToPostIfNeeded` function had a bug where it didn't really wait till the `MinAssertionPeriodBlocks` is reached since the parent assertion was created. This PR fixes that bug and modifies the implementation to regularly check if the target block number is reached instead of assuming that the average block time is perfect and waiting for that many block-times.
Corresponding nitro PR- https://github.com/OffchainLabs/nitro/pull/2818
Part of NIT-2960
> Fix waitToPostIfNeeded to regularly check if the target block number is reached

- assertions/poster.go
- chain-abstraction/sol-implementation/assertion_chain.go
- chain-abstraction/sol-implementation/transact.go
- challenge-manager/edge-tracker/challenge_confirmation.go
Not using context cancel in a select block leads to issues in preventing graceful shutdown
> Respect Context Cancel in time.After Invocations

- README.md
**"For our a technical" → "For our technical"**
> Corrected "For our a technical" to "For our technical" in the relevant section.
**"Merkleizatins" → "Merkleizations"**
> Fixed the typo "Merkleizatins" to "Merkleizations".
**"Alternatively, tests can be ran" → "Alternatively, tests can be run with Bazel as follows:"**
> Corrected the grammatical error in the sentence "Alternatively, tests can be ran" to "Alternatively, tests can be run with Bazel as follows:".
**"[https://pkg.go.dev/github.com/OffchainLabs/bold]" → "(https://pkg.go.dev/github.com/OffchainLabs/bold)"**
> Fixed the link formatting for the Go documentation URL.
**"(./LICENSE)" → "(./LICENSE.md)"**
> Corrected the file path for the LICENSE file to include the correct .md extension.
> Fix Grammar, Spelling, and Formatting Issues

- api/backend/backend.go
- api/server/methods.go
- assertions/confirmation.go
- assertions/sync.go
- chain-abstraction/interfaces.go
- chain-abstraction/sol-implementation/assertion_chain.go
- chain-abstraction/sol-implementation/edge_challenge_manager.go
- chain-abstraction/sol-implementation/transact.go
- chain-abstraction/sol-implementation/types.go
- challenge-manager/chain-watcher/watcher.go
- challenge-manager/challenge-tree/mock/edge.go
- challenge-manager/edge-tracker/challenge_confirmation.go
- testing/mocks/BUILD.bazel
- testing/mocks/mocks.go
This PR fixes a bug in the functions `waitForTxToBeSafe` inside the BoLD repo. These functions used to check that a tx receipt has passed a configured, `safe` block number. However, in a bad merge, it was edited to just compare against `latest`, which was incorrect. This led to a variety of UX issues in the BoLD v2 testnet and more egregious errors around attempting to send a ton of timer update txs at the end of a challenge.
This PR also fixes the DB methods to use `latest` block number, as it is important our DB captures all data that is posted, even if it is reorged later. The DB does not need to be reorg safe as it is purely for informational purposes and data analysis. We also a removed a method to fetch the latest confirmed assertion via the rest API, as this can easily be retrieved …
> Improve Issues Around Waiting for Safe Txs

- assertions/poster.go
- assertions/sync.go
- chain-abstraction/interfaces.go
- chain-abstraction/sol-implementation/assertion_chain.go
- challenge-manager/chain-watcher/watcher.go
- challenge-manager/challenge-tree/paths.go
- challenge-manager/edge-tracker/tracker.go
- testing/endtoend/e2e_crash_test.go
- testing/endtoend/e2e_test.go
- testing/mocks/mocks.go
This PR discovered that the chain watcher, which scrapes for challenge events from the chain, was not respecting the desired RPC block number configured by the user. For instance, if the software were configured to rely on finalized data, the watcher would just look at latest data and lead to errors at runtime when scraping chain events. Although non-critical, these are still important error logs to avoid in normal operation.
This PR also fixes a bit of log formatting and removes a certain condition of an edge's children not yet being tracked from being an error log. This also occurs when relying on finalized data, but resolves on its own
> Use Desired RPC Block Number in Chain Watcher

- assertions/manager.go
- testing/endtoend/e2e_crash_test.go
- testing/endtoend/e2e_test.go
- testing/endtoend/expectations.go
BoLD now does a few things on startup in the assertion manager that should not be done if the node is configured as a watchtower. This was caught on BoLD testnet v2
> Disable Staking on Startup if Watchtower

- assertions/manager.go
- chain-abstraction/interfaces.go
- chain-abstraction/sol-implementation/assertion_chain.go
- chain-abstraction/sol-implementation/assertion_chain_test.go
- testing/mocks/mocks.go
This PR fixes a bug where auto-depositing stake token (wrapping ETH to WETH) was checking balances using "finalized" data, and not checking if the validator was already staked. This would lead to a situation where if the validator deposits, then the process restarts, the validator will attempt to deposit a second time because the tx is not yet final. Moreover, it should not even attempt an auto-deposit if already staked.
> Skip AutoDeposit if Staked, Use Latest Data for Auto-Operations

- assertions/poster.go
- assertions/sync.go
This just cuts down on log-spam slightly. Without the sleep, there were sometimes hundreds of log lines saying that the chain was still catching up. And, that means there were also a bunch of tight RPC calls.
> Add a small sleep (1/10 average block time) when chain is behind

- chain-abstraction/sol-implementation/assertion_chain.go
- chain-abstraction/sol-implementation/assertion_chain_test.go
The new stake function was untested, and is important for automating delegated stakers. A boolean was incorrect, and the wrong value was passed into the actual staking mechanism
> Fix New Stake Method

- assertions/confirmation.go
- assertions/poster.go
- challenge-manager/chain-watcher/watcher.go
related to NIT-3129
Pulled in https://github.com/OffchainLabs/nitro/pull/2976
> Only log gas estimation error for assertion creation/confirmation if persistent

- assertions/confirmation.go
- assertions/poster.go
- challenge-manager/chain-watcher/watcher.go
Previously we were not resetting handlers for gasEstimation related ephemeral error of the form `gas estimation errored for tx with hash`, this meant these errors were unnecessarily loud, this PR fixes this by correctly resetting such handlers.
There was another issue in `chain-watcher/watcher.go` where the `FilterOpts` for corresponding `FilterLogs` query would have incorrect start and end values during a reorg (as there is a possibility for `toBlock` to fall behind `fromBlock`), thus leading to avoidable loud errors- 
```
{"t":"2025-03-17T06:08:30.39179413Z","lvl":"error","msg":"Could not check for edge added","err":"invalid block range params"}
```
fixed by rewinding `fromBlock` to `toBlock`.
Corresponding Nitro PR- https://github.com/OffchainLabs/nitro/pull/3032
Part of NIT-3148
> Correctly reset handlers for gasEstimation related ephemeral error and fix Start and End values in FilterLogs query

- chain-abstraction/sol-implementation/assertion_chain.go
Every other place in the BoLD repo lets a user customize the parent chain block time on initialization, _except_ the assertion chain. This blocks L3 support for BoLD
> Expose a Parent Chain Block Time Option for the Assertion Chain Struct in BoLD

- testing/endtoend/backend/anvil_local.go
- testing/setup/rollup_stack.go
This PR adds the option to toggle whether or not a bold chain supports blobs, which is important for Orbit chain and custom setups
> Add an Option to Toggle Blob Support in BoLD Deployment Tooling

- assertions/sync.go
- runtime/retry.go
This PR makes it that the BoLD retry error in not finding message results for future blocks is logged as a warning instead as an error. Below is the log line that will be logged at warning and other errors would continue to log at level Error.
```
Could not succeed function after retries retryCount=15 err="<validator-name>: could not check if we have result at count <msgIndex>: result not found" 
```
Corresponding nitro PR- https://github.com/OffchainLabs/nitro/pull/3171
Part of NIT-3158
> Support logging at different level for ephemeral BoLD errors

- assertions/manager_test.go
- assertions/poster.go
- assertions/poster_test.go
- assertions/sync.go
related to: NIT-3296
Pulled in https://github.com/OffchainLabs/nitro/pull/3183
Refractor PostAssertionBasedOnParent to avoid calling ReadAssertionCreationInfo
This is done so that when `PostAssertionBasedOnParent` is called by `PostAssertion`, it does not error out due to `GetAssertionCreationParentBlock` being called giving error `ASSERTION_NOT_EXIST` on finalized block.
This is safe to do since `PostAssertion` does not need `AssertionCreationParentBlock` anywhere in the flow.
> Refractor PostAssertionBasedOnParent to avoid calling ReadAssertionCreationInfo

- chain-abstraction/sol-implementation/assertion_chain.go
`creationL1Block` should not be the parent chain block for a L3 orbit chains, the `CreatedAtBlock` field in the assertion node object is always a L1 block number (or the block number of the first ancestor non-arbitrum chain)
Pulled in https://github.com/OffchainLabs/nitro/pull/3242
> fix: creationL1Block

- assertions/manager.go
Context https://offchainlabs.slack.com/archives/C048E5TQB5L/p1747908074364599
Calculation for safeBlockDelayInSeconds was not accurate for L3s using BoLD. It was taking L2 block numbers and multiplying by L1 block times, so it was triggering that warning sooner than expected. 
Pulled in https://github.com/OffchainLabs/nitro/pull/3257
Related to: NIT-3396
> Fix safeBlockDelayInSeconds calculation for L3

- assertions/sync.go
Related to NIT-3523
Pulled in https://github.com/OffchainLabs/nitro/pull/3397
`ProcessAllAssertionsInRange` is called in two scenarios:
1. **During startup** — when the system processes from the last confirmed assertion to the latest block.
* This case was already handled by splitting the `getLogs` query into smaller batch `FilterOpts` to avoid exceeding the block limit.
2. **During regular polling** — when the system polls at a configured interval.
* The assumption was that regular polling would naturally limit the batch size. However, since the polling interval is configurable, the block range could still exceed the limit.
This PR ensures that even during the polling flow, `getLogs` queries are broken down into smaller batch `FilterOpts`, preventing potential block limit issues in both …
> Call processAllAssertionsInRange with small batch filterOpts
