OffchainLabs/bold

api/BUILD.bazel
api/assertions.go
api/data.go
api/data_test.go
api/edges.go
api/method_assertions.go
api/method_assertions_test.go
api/method_edges.go
api/method_edges_test.go
api/method_healthz_test.go
api/server.go
api/server_test.go
chain-abstraction/execution_state.go
chain-abstraction/interfaces.go
chain-abstraction/sol-implementation/assertion_chain.go
chain-abstraction/sol-implementation/assertion_chain_test.go
challenge-manager/manager.go
testing/mocks/mocks.go

This PR implements ListAssertions to return all assertions since the last confirmed assertion.
This PR also includes the addition of LatestCreatedAssertionHashes from #404. 
Example response from e2e (formatted for humans):
```json
[
{
"confirmPeriodBlocks": 25,
"requiredStake": "100",
"parentAssertionHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
"inboxMaxCount": "1",
"afterInboxBatchAcc": "0x0000000000000000000000000000000000000000000000000000000000000000",
"assertionHash": "0x73511b5292c9a73729fd9d9c78c78465c0a2c5f587ed26b1737224d0b63d5338",
"wasmModuleRoot": "0x0000000000000000000000000000000000000000000000000000000000000000",
"challengeManager": "0x05242d4ac717cdf38c36af290f2b0da99aa82c67",
"creationBlock": 16,
"transactionHash": …
```

API: Implement ListAssertions 

---

assertions/poster.go
assertions/scanner.go
challenge-manager/chain-watcher/watcher.go
challenge-manager/challenges.go
challenge-manager/edge-tracker/tracker.go

This PR fixes incorrect error logging by using `log.Ctx`

fix: srv log error

---

contracts/src/precompiles/ArbGasInfo.sol
contracts/src/precompiles/ArbOwnerPublic.sol

This PR port 2 PRs from the nitro-contracts repo, including:
https://github.com/OffchainLabs/nitro-contracts/pull/44
https://github.com/OffchainLabs/nitro-contracts/pull/46
Only changing precompile interfaces

chore: port nitro contracts pr 2

---

challenge-manager/chain-watcher/BUILD.bazel
time/time_reference_test.go

Add time reference tests. Improve test coverage to 100%

Add time reference tests

---

challenge-manager/chain-watcher/BUILD.bazel
containers/threadsafe/BUILD.bazel
containers/threadsafe/map_test.go
containers/threadsafe/set_test.go
containers/threadsafe/slice_test.go

This PR adds tests for thread-safe methods. Improve test coverage from 53% to 97%

Add tests for thread safe util pkg

---

challenge-manager/chain-watcher/BUILD.bazel
challenge-manager/chain-watcher/watcher.go
challenge-manager/chain-watcher/watcher_test.go
deps.bzl
go.mod
go.sum

Reverts OffchainLabs/bold#452 breaks e2e

Revert "Add LRU Cache for `agreesWithStart` in `AddEdge`"

---

assertions/poster.go
assertions/poster_test.go

Reason explained in detail here
https://www.notion.so/arbitrum/Deep-Dive-Into-Arbitrum-BOLD-Assertions-febf4f6b2dc74524912c156bfcb28acb?pvs=4#90d4facb34474f99964d99c9f1634017

Find latest valid assertion on all branch rather than just one

---

contracts/test/challengeV2/ChallengeEdgeLib.t.sol

* No new tests, just refactored so that coverage picks them up

Refactored challenge edge tests

---

contracts/scripts/files/localConfig.json
contracts/scripts/files/mainnetConfig.json

Updated to 4 big step levels of depth 9 and 1 small step level of depth 7

Updated number of big step levels

---

api/data.go
api/data_test.go
api/method_edges.go
api/method_edges_test.go
api/server.go
challenge-manager/chain-watcher/watcher.go
testing/endtoend/basic_local_test.go

Part of https://www.notion.so/arbitrum/Crafting-an-API-for-Inspecting-Challenges-in-Arbitrum-BOLD-006da164d7ae450393b611d2777ff860

Add API for getting honest vs all edges

---

assertions/scanner.go

This was causing duplicated assertion confirmation checks

While checking for AssertionAdded, make sure to go over every block exactly once

---

chain-abstraction/sol-implementation/types.go

This PR fixes a serious issue that would lead edges thinking they are confirmable when they are not. It turns out we were using the wrong assertion timer to confirm edges because of this function. With this change, we can make sure we are returning the parent assertion hash when a.PrevId() is called

Fix the PrevId() method of an Assertion to Use ParentAssertionHash

---

contracts/test/challengeV2/ChallengeEdgeLib.t.sol

this line has caused problems with stack too deep when adding to the ChallengeEdge struct

Stack too deep fix

---

api/server/BUILD.bazel
api/server/server.go
assertions/BUILD.bazel
assertions/confirmation.go
assertions/manager.go
assertions/manager_test.go
assertions/poster_test.go
challenge-manager/BUILD.bazel
challenge-manager/chain-watcher/BUILD.bazel
challenge-manager/chain-watcher/watcher.go
challenge-manager/challenges.go
challenge-manager/manager.go
testing/endtoend/e2e_test.go
util/stopwaiter/BUILD.bazel
util/stopwaiter/stopwaiter.go

Added stopwaiter based on nitro implementation https://github.com/OffchainLabs/nitro/blob/master/util/stopwaiter/stopwaiter.go

[NIT-2126] Add and use stopwaiter

---

assertions/manager.go
assertions/poster.go
assertions/sync.go
chain-abstraction/sol-implementation/assertion_chain.go
challenge-manager/chain-watcher/watcher.go
challenge-manager/challenges.go
challenge-manager/edge-tracker/tracker.go

Thanks to feedback from @leeederek !

Log Revamp for Testnet

---

contracts/config.ts.example
contracts/createERC20Rollup.ts
contracts/createEthRollup.ts
contracts/deploy/BridgeCreator.js
contracts/deploy/BridgeStubCreator.js
contracts/deploy/HashProofHelper.js
contracts/deploy/InboxStubCreator.js
contracts/deploy/OneStepProofEntryCreator.js
contracts/deploy/OneStepProver0Creator.js
contracts/deploy/OneStepProverHostIoCreator.js
contracts/deploy/OneStepProverMathCreator.js
contracts/deploy/OneStepProverMemoryCreator.js
contracts/deploy/SequencerInbox.js
contracts/deploy/SequencerInboxStubCreator.js
contracts/deploy/ValueArrayTesterCreator.js
contracts/deployment.ts
contracts/deploymentUtils.ts
contracts/package.json
contracts/scripts/genNetwork.ts
contracts/scripts/rollupCreation.ts
contracts/scripts/testSetup.ts
contracts/yarn.lock

Port some of the remaining scripts from nitro-contracts

Add missing nitro-contracts scripts

---

containers/in-progress-cache/cache.go
containers/in-progress-cache/cache_test.go

This fixes the validator getting stuck issue after getting "not connected" error https://grafana.sso.arbitrum.io/goto/5PF3ZU-SR?orgId=1

Handle errored case for the in progress cache compute

---

contracts/src/assertionStakingPool/AssertionStakingPoolCreator.sol
contracts/src/assertionStakingPool/EdgeStakingPoolCreator.sol
contracts/src/assertionStakingPool/StakingPoolCreatorUtils.sol

staking pool creator refactor

---

contracts/src/rollup/BOLDUpgradeAction.sol

Original author @shotaronowhere and full PR credit
"since force inclusion now depends on block numbers alone, it's important that delayBlocks is consistent with delaySeconds to ensure the force inclusion window does not inadvertently decrease."

fix: update delayBlocks in bold upgrade actions 

---

chain-abstraction/sol-implementation/assertion_chain.go

This should be implemented on the nitro side

Remove DataPosterTransactor

---

challenge-manager/chain-watcher/watcher.go
challenge-manager/manager_test.go
challenge-manager/stack.go

Pulled in https://github.com/OffchainLabs/nitro/pull/2951

Use last confirm assertion in watcher to find the starting point

---

chain-abstraction/sol-implementation/assertion_chain.go

related to NIT-2971
pulled in https://github.com/OffchainLabs/nitro/pull/2967

Handle getting creationAtBlock for l3

---

chain-abstraction/sol-implementation/assertion_chain.go

Pulled in https://github.com/OffchainLabs/nitro/pull/3242

fix: AssertionUnrivaledBlocks

---

runtime/BUILD.bazel
runtime/retry.go

related to NIT-3350
pulled in https://github.com/OffchainLabs/nitro/pull/3223

Reduce error logs when retrying

---

go.mod

Pulled in by https://github.com/OffchainLabs/nitro/pull/3426

Use go 1.24.5
